# Codemagic workflow for EMFAD Analyzer Android App

workflows:
  android-build:
    name: Android Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      vars:
        CM_JAVA_VERSION: "17"
        CM_ANDROID_SDK_BUILD_TOOLS: "34.0.0"
        CM_ANDROID_SDK_PLATFORM: "34"
      java: 17
      # android_signing:
      #   - keystore_reference  # Uncomment and replace with your actual keystore reference
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: 'master'
          include: true
          source: true
        - pattern: 'develop'
          include: true
          source: true
        - pattern: 'feature/*'
          include: true
          source: true
    scripts:
      - name: Set up local.properties
        script: | 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Check project structure
        script: | 
          ls -la
          echo "Checking for gradlew..."
          if [ ! -f "./gradlew" ]; then
            echo "gradlew not found, generating wrapper..."
            gradle wrapper --gradle-version 8.2.1
          fi
          chmod +x ./gradlew
      - name: Get dependencies
        script: | 
          ./gradlew dependencies
      - name: Build debug APK
        script: | 
          ./gradlew assembleDebug
      - name: Build release APK
        script: | 
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab
      - app/build/outputs/**/mapping.txt
    publishing:
      email:
        recipients:
          - your.email@example.com
        notify:
          success: true
          failure: true

  android-test:
    name: Android Tests
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      vars:
        CM_JAVA_VERSION: "17"
        CM_ANDROID_SDK_BUILD_TOOLS: "34.0.0"
        CM_ANDROID_SDK_PLATFORM: "34"
      java: 17
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: 'master'
          include: true
          source: true
        - pattern: 'develop'
          include: true
          source: true
        - pattern: 'feature/*'
          include: true
          source: true
    scripts:
      - name: Set up local.properties
        script: | 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Check project structure and setup Gradle
        script: | 
          ls -la
          echo "Checking for gradlew..."
          if [ ! -f "./gradlew" ]; then
            echo "gradlew not found, generating wrapper..."
            gradle wrapper --gradle-version 8.2.1
          fi
          chmod +x ./gradlew
          echo "Available Gradle tasks:"
          ./gradlew tasks --all
      - name: Get dependencies
        script: | 
          ./gradlew dependencies
      - name: Run unit tests (if available)
        script: | 
          echo "Checking for test tasks..."
          if ./gradlew tasks --all | grep -q "testDebugUnitTest\|test "; then
            echo "Running unit tests..."
            ./gradlew testDebugUnitTest || ./gradlew test || echo "No unit tests to run"
          else
            echo "No unit test tasks found - skipping"
          fi
      - name: Generate test report (if available)
        script: | 
          if ./gradlew tasks --all | grep -q "jacocoTestReport"; then
            echo "Generating test coverage report..."
            ./gradlew jacocoTestReport || echo "Could not generate test report"
          else
            echo "JaCoCo test report task not available - skipping"
          fi
    artifacts:
      - app/build/reports/**/*.xml
      - app/build/reports/**/*.html
      - app/build/test-results/**/*.xml
    publishing:
      email:
        recipients:
          - your.email@example.com
        notify:
          success: false
          failure: true

  android-instrumented-test:
    name: Android Instrumented Tests
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      vars:
        CM_JAVA_VERSION: "17"
        CM_ANDROID_SDK_BUILD_TOOLS: "34.0.0"
        CM_ANDROID_SDK_PLATFORM: "34"
      java: 17
      # android_signing:
      #   - keystore_reference  # Uncomment and replace with your actual keystore reference
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'master'
          include: true
          source: true
        - pattern: 'develop'
          include: true
          source: true
    scripts:
      - name: Set up local.properties
        script: | 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Check project structure and setup Gradle
        script: | 
          ls -la
          echo "Checking for gradlew..."
          if [ ! -f "./gradlew" ]; then
            echo "gradlew not found, generating wrapper..."
            gradle wrapper --gradle-version 8.2.1
          fi
          chmod +x ./gradlew
      - name: Get dependencies
        script: | 
          ./gradlew dependencies
      - name: Build debug APK for testing
        script: | 
          ./gradlew assembleDebug
          ./gradlew assembleDebugAndroidTest
      - name: Launch emulator and run instrumented tests
        script: | 
          cd $ANDROID_SDK_ROOT/emulator
          echo "Available AVDs:"
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/avdmanager list avd
          echo "Starting emulator..."
          $ANDROID_SDK_ROOT/emulator/emulator -avd test -no-audio -no-window &
          adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed | tr -d '\r') ]]; do sleep 1; done; input keyevent 82'
          echo "Emulator is ready"
          ./gradlew connectedDebugAndroidTest
    artifacts:
      - app/build/reports/**/*.xml
      - app/build/reports/**/*.html
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your.email@example.com
        notify:
          success: false
          failure: true
